const AJAX_RESPONSE_OK = 1;
const AJAX_RESPONSE_NOT_FILLED = 2;
const AJAX_RESPONSE_ERR = 3;

const AJAX_RESPONSE_PLACE_NEW = 1;
const AJAX_RESPONSE_PLACE_PREPEND = 2;
const AJAX_RESPONSE_PLACE_APPEND = 3;

const AJAX_REQUEST_EXCLUDE = 1;
const AJAX_REQUEST_INCLUDE = 2;
const AJAX_REQUEST_CHECK_NEW = 3;
const AJAX_REQUEST_CHECK_PREV = 4;
