version: '3'

networks:
  myztt:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  nginx:
    restart: always
    container_name: mnginx
    build:
      context: ./
      dockerfile: ./docker/nginx/nginx.docker
    ports:
      - "80:80"
    networks:
      myztt:
        ipv4_address: 172.18.0.100
    volumes:
      - ./:/var/www/html/ztt.loc
  php-fpm:
    restart: always
    container_name: mphp
    build:
      context: ./
      dockerfile: ./docker/php/php-fpm.docker
    volumes:
      - ./:/var/www/html/ztt.loc
    networks:
      myztt:
        ipv4_address: 172.18.0.101
#  db:
#    image: mysql:8.0
#    container_name: msql8
#    # command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: rO0tExample
#      MYSQL_USER: jackson
#      MYSQL_PASSWORD: j@ck5On
##    volumes:
##      - mysql_data:/var/lib/mysql
  redis:
    build:
      context: ./
      dockerfile: ./docker/redis_data/redis.docker
    container_name: mredis
    restart: always
    networks:
      myztt:
        ipv4_address: 172.18.0.103
  #    volumes:
#      - redis_data:/data
#  memcached:
#    #image: 'memcached:alpine'
#    image: memcached:1.6.17
#    container_name: mymemcached
#    restart: always
#    command: "-p 11211 -m 256 -c 8092"
#    ports:
#      - "11211:11211"
#    networks:
#      default:
#        ipv4_address: 127.0.0.1

#  mongodb:
#    image: 'mongo:6.0-focal'
#    container_name: mymongodb
#    restart: always
#    ports:
#      - "27017:27017"
#    volumes:
#      - 'mongodb_data:/bitnami'
#  clickhouse:
#    image: 'bitnami/clickhouse:22.3.14'
#    container_name: myclickhouse
#    hostname: clickhouse
#    restart: always
