version: '3'

networks:
  myztt:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  nginx:
    restart: "no"
    container_name: mnginx
    build:
      context: ./
      dockerfile: ./docker/nginx/nginx.docker
    ports:
      - "80:80"
    networks:
      myztt:
        ipv4_address: 172.18.0.100
    volumes:
      - ./:/var/www/html/ztt.loc
  php-fpm:
    restart: "no"
    container_name: mphp
    build:
      context: ./
      dockerfile: ./docker/php/php-fpm.docker
    volumes:
      - ./:/var/www/html/ztt.loc
    networks:
      myztt:
        ipv4_address: 172.18.0.101
    environment:
      - USERMAP_UID=1000
      - USERMAP_GID=1000
  db:
    image: mysql:8.0
    container_name: msql8
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rO0tExample
      MYSQL_USER: jackson
      MYSQL_PASSWORD: j@ck5On
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      myztt:
        ipv4_address: 172.18.0.102
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  redis:
    build:
      context: ./
      dockerfile: docker/redis/redis.docker
    container_name: mredis
    restart: "no"
    networks:
      myztt:
        ipv4_address: 172.18.0.103
    volumes:
      - ./docker/redis/data:/data
  memcached:
    image: memcached:1.6.17
    container_name: mymemcached
    restart: "no"
    command: "-p 11211 -m 256 -c 8092"
    networks:
      myztt:
        ipv4_address: 172.18.0.104

#  mongodb:
#    image: 'mongo:6.0-focal'
#    container_name: mymongodb
#    restart: no
#    ports:
#      - "27017:27017"
#    volumes:
#      - 'mongodb_data:/bitnami'
#  clickhouse:
#    image: 'bitnami/clickhouse:22.3.14'
#    container_name: myclickhouse
#    hostname: clickhouse
#    restart: no
